apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: isc-oren
  namespace: ngrok-eks
spec:
  destination:
    namespace: prod-eks
    server: https://9BDA6CC27C15703B31AFF558AD197407.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    repoURL: https://github.com/noam-codefresh/shared-gh
    path: resources
    dir:
      include: {all/**/*.yaml,all/*.yaml}
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
